---
title: "ggplot_exercise"
output: html_notebook
---

## This is a notebook about ggplot. I reviewed my knowledge about using ggplot!

#preparing libary and dataset
```{r}
library(ggplot2)
```

```{r}
#we use this dataset
bar_df<-data.frame(obs=1:10, #1 to 10 number
                   var=rep(c("A","B","C"),length.out=10), #length.out option, set length of vector
                   value=sample(1:100,size=10),
                   stringsAsFactors=FALSE
                   )
bar_df
```


```{r}
ggplot(data=bar_df, aes(x=obs, y=value,group=var,color=var))+ #common options
  geom_line(size=1.3)+geom_point(size=3)
```

### color vs fill

color : 1-dimension option, point, line

fill : 2-dimension option, plane

```{r}
ggplot(data=bar_df,aes(x=obs,y=value))+geom_col() #default bar graph
ggplot(data=bar_df,aes(x=obs,y=value,fill=value))+geom_col() #if use color option, edge changes 
ggplot(data=bar_df,aes(x=obs,y=value,fill=as.factor(value)))+geom_col() #as factor
ggplot(data=bar_df,aes(x=as.factor(obs),y=value,fill=as.factor(value)))+geom_col()
ggplot(data=bar_df,aes(x=var,y=value,fill=as.factor(value)))+geom_col(position="stack") 
ggplot(data=bar_df,aes(x=var,y=value,fill=as.factor(value)))+geom_col(position="dodge")
```

### change color
```{r}
ggplot(data=bar_df,aes(x=obs,y=value))+geom_line(aes(color=value),size=1)
ggplot(data=bar_df,aes(x=obs,y=value))+geom_line(aes(color=var),size=1)+scale_color_brewer(palette=3) #scale_color_grey(start=0.2,end=0.8)
#manual color
ggplot(data=bar_df,aes(x=obs,y=value))+geom_line(aes(color=var),size=1)+scale_color_manual(values=c("A"="red","B"="green","C"="blue"))
```

### x,y axis setting

```{r}
ggplot(data=bar_df, aes(x=var,y=value,fill=value))+
  geom_col()+
  scale_x_discrete(expand=c(0.01,0.01))+
  scale_y_continuous(expand=c(0.5,0.5))
#x는 discrete variable, y는 continuous variable. setting은 같다. expand 에는 c(x,x)두 값을 써줘야한다. 값이 클 수록 여백이 커진다. 여백이 작아지면 그래프의 내용이 강조된다. 

bar_df
ggplot(data=bar_df,aes(x=obs,y=value,color=value))+geom_line(size=2)+scale_x_continuous(limits=c(0,12), breaks=c(5,10),label=c(5,10)) #limit 밖의 값은 짤린다, 눈금을 내가 
#수열생성함수로 만들 수도 있다. breaks=seq(0,100,10), labels=seq(0,100,10)
#breaks=(0:5)*20 이렇게도 할 수 있다. 

```
### 요소 설정

```{r}
ggplot(data=bar_df,aes(x=obs,y=value,shape=var))+geom_point(aes(color=value),size=10)
ggplot(data=bar_df,aes(x=obs,y=value,shape=var))+geom_point(aes(color=value),size=10)+
  scale_shape_manual(values=c("A"=1,"B"=5,"C"="헐"))
```

### 텍스트 설정

```{r}
ggplot(data=bar_df,aes(x=obs,y=value,color=value))+
  geom_point(size=10)+
  labs(title="title is this",
       subtitle="subtitle is this",
       x="x axis",
       y="y axis",
       color="color is this")+
  theme(title=element_text(size=50),
        axis.title=element_text(size=30,
                                face="italic",
                                angle=45), #angle 은 x axis 에만 적용된다.
        axis.title.x=element_text(vjust=0.5),
        axis.title.y=element_text(hjust=0.8, angle=90),
        axis.text=element_text(size=50,face="bold"))
#x축을 없애고 싶으면 ,theme option에 axis.title.x=element_blank()
```

### 덧그리기

```{r}
ggplot(data=bar_df,aes(x=obs,y=value,color=value))+
  geom_point(size=10)+
  geom_hline(yintercept=10,size=2, color="green",alpha=0.7,linetype=1)+
  geom_hline(yintercept=30,size=2, color="green",alpha=0.7,linetype=2)+
  geom_hline(yintercept=50,size=2, color="green",alpha=0.7,linetype=3)+
  geom_hline(yintercept=70,size=2, color="green",alpha=0.7,linetype=4)+
  geom_hline(yintercept=90,size=2, color="green",alpha=0.7,linetype=5)+
  geom_hline(yintercept=100,size=2, color="green",alpha=0.7,linetype=6)+
  geom_vline(xintercept=5,linetype=10)+
  annotate(geom="text",label="abcd",size=10,x=7,y=20)+ #좌표는 글자의 정중앙의 좌표다. 
  annotate(geom="rect",fill="yellow",xmin=1,xmax=3,ymin=20,ymax=60)+
  annotate(geom="segment",fill="red",x=10,xend=8, y=100,yend=10)+ #선분
  annotate(geom="pointrange",color="purple",size=2,x=3,y=10,ymin=5,ymax=20)
  
```


### 범례

```{r}
ggplot(data=bar_df,aes(x=obs,y=value,color=value,shape=var))+geom_point(size=10)+
  theme(legend.position="bottom",#left right top bottom
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        legend.key.size=unit(x=0.5,units="cm") #legend.key.width, legend.key.height
  )
```

